version: '3'
services:
  
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MZth2BRdEpAI
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
      
volumes:
  dragonflydata:
  db:
    driver: local