micronaut:
  application:
    name: phones
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /res/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      swagger-ui-res:
        paths: classpath:META-INF/swagger/views/swagger-ui/res
        mapping: /res/**
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASS:MZth2BRdEpAI}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
r2dbc:
  datasources:
    default:
      dialect: POSTGRES
      db-type: postgres
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:5432}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:MZth2BRdEpAI}
      database: ${DB_NAME:postgres}
      driver: postgresql
redis.uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
flyway:
  datasources:
    default:
      enabled: true
